// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'change_user_password_model.g.dart';

@JsonSerializable()
class ChangeUserPasswordModel {
  final String? id;
  final String? oldPassword;
  final String? newPassword;
  final String? confirmNewPassword;

  ChangeUserPasswordModel({
    this.id,
    this.oldPassword,
    this.newPassword,
    this.confirmNewPassword,
  });

  factory ChangeUserPasswordModel.fromJson(Map<String, dynamic> json) =>
      _$ChangeUserPasswordModelFromJson(json);

  Map<String, dynamic> toJson() => _$ChangeUserPasswordModelToJson(this);

  ChangeUserPasswordModel copyWith({
    String? id,
    String? oldPassword,
    String? newPassword,
    String? confirmNewPassword,
  }) {
    return ChangeUserPasswordModel(
      id: id ?? this.id,
      oldPassword: oldPassword ?? this.oldPassword,
      newPassword: newPassword ?? this.newPassword,
      confirmNewPassword: confirmNewPassword ?? this.confirmNewPassword,
    );
  }
}
