// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'add_comment_model.g.dart';

@JsonSerializable()
class AddCommentModel {
  final String authorId;
  final String postId;
  final String content;

  AddCommentModel({
    required this.authorId,
    required this.postId,
    required this.content,
  });

  factory AddCommentModel.fromJson(Map<String, dynamic> json) =>
      _$AddCommentModelFromJson(json);

  Map<String, dynamic> toJson() => _$AddCommentModelToJson(this);
}
