// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'comment_like.g.dart';

@JsonSerializable()
class CommentLikeModel {
  final String userId;
  final String commentId;

  CommentLikeModel({
    required this.userId,
    required this.commentId,
  });

  factory CommentLikeModel.fromJson(Map<String, dynamic> json) =>
      _$CommentLikeModelFromJson(json);

  Map<String, dynamic> toJson() => _$CommentLikeModelToJson(this);
}
