// Generated by https://quicktype.io

import 'package:dd_study_22_ui/domain/models/simple_user/simple_user.dart';
import 'package:json_annotation/json_annotation.dart';

part 'comment_model.g.dart';

@JsonSerializable()
class CommentModel {
  final String id;
  final SimpleUser author;
  final String content;
  final int likes;
  final int isLiked;
  final DateTime publishDate;

  CommentModel({
    required this.id,
    required this.author,
    required this.content,
    required this.likes,
    required this.isLiked,
    required this.publishDate,
  });

  factory CommentModel.fromJson(Map<String, dynamic> json) =>
      _$CommentModelFromJson(json);

  Map<String, dynamic> toJson() => _$CommentModelToJson(this);
}
