// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'post_like.g.dart';

@JsonSerializable()
class PostLikeModel {
  final String userId;
  final String postId;

  PostLikeModel({
    required this.userId,
    required this.postId,
  });

  factory PostLikeModel.fromJson(Map<String, dynamic> json) =>
      _$PostLikeModelFromJson(json);

  Map<String, dynamic> toJson() => _$PostLikeModelToJson(this);
}
